In [1]:
#first analysis

import pandas as pd

df = pd.read_parquet("/Users/andrea/Progetti/pulsewave/data/reverb/test/used-IT/combined_dataset.parquet")

In [2]:
df.shape

(164441, 29)

In [3]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164441 entries, 0 to 164440
Data columns (total 29 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       164441 non-null  int64
 1   make                     164441 non-null  object
 2   model                    164441 non-null  object
 3   finish                   164441 non-null  object
 4   year                     164441 non-null  object
 5   sku                      164441 non-null  object
 6   product_type             164441 non-null  object
 7   category                 164441 non-null  object
 8   title                    164441 non-null  object
 9   created_at               164441 non-null  datetime64[ns, UTC]
 10  shop_slug                164441 non-null  object
 11  preferred_seller         164441 non-null  bool
 12  condition                164441 non-null  object
 13  offers_enabled           164441 non-null  bool
 14  has_inventory            164441 non-null  bool
 15  inventory                164441 non-null  int64
 16  published_at             164441 non-null  datetime64[ns, UTC]
 17  state                    164441 non-null  object
 18  auction                  164441 non-null  bool
 19  permalink                164441 non-null  object
 20  price                    164441 non-null  object
 21  price_currency           164441 non-null  object
 22  price_taxIncluded        164441 non-null  bool
 23  buyer_price              164441 non-null  object
 24  buyer_price_currency     164441 non-null  object
 25  buyer_price_taxIncluded  164441 non-null  bool
 26  snap_valid_from          164441 non-null  datetime64[ns, UTC]
 27  snap_valid_to            31 non-null      datetime64[us, UTC]
 28  snap_is_current          164441 non-null  bool
dtypes: bool(7), datetime64[ns, UTC](3), datetime64[us, UTC](1), int64(2), object(16)
memory usage: 173.1 MB

In [8]:
price_stats = df.groupby('product_type').agg({
    'price': ['mean', 'median', 'min', 'max', 'count'],
    'buyer_price': ['mean', 'median']
}).round(2)
price_stats

                        price                                    buyer_price  \
                         mean   median    min         max  count        mean
product_type
accessories            102.58    27.36   1.50    60000.00  10934       99.32
acoustic-guitars      3190.37  1550.00   5.46   250000.00  12000     3166.57
amps                  1578.07   701.10   6.56  1748652.73   7723     1571.80
band-and-orchestra    1292.69   448.59   2.00    80748.42   6081     1285.39
bass-guitars          2300.59  1386.14  43.77    84405.78   9070     2285.15
dj-and-lighting-gear   742.85   205.65   7.66    19886.54   1404      724.00
drums-and-percussion   420.36   170.46   1.00    26916.14  14795      417.18
effects-and-pedals     285.63   168.27   3.00   897203.74  28866      283.32
electric-guitars      3711.83  2090.22  13.40   897206.42   9329     3668.81
folk-instruments       956.23   389.50   3.28    39999.00   3234      945.73
home-audio            1084.93   250.00   2.18   175000.00   3925     1082.98
keyboards-and-synths  1067.88   313.12   1.09   198959.33  20560     1063.53
parts                  245.94   103.99   2.18    22000.00  18702      234.64
pro-audio             1140.75   330.00   2.19   140651.00  17818     1129.94


                       median
product_type
accessories             23.25
acoustic-guitars      1525.24
amps                   700.00
band-and-orchestra     447.71
bass-guitars          1364.22
dj-and-lighting-gear   190.65
drums-and-percussion   169.66
effects-and-pedals     166.39
electric-guitars      2062.14
folk-instruments       373.22
home-audio             250.00
keyboards-and-synths   310.00
parts                   93.59
pro-audio              327.54

In [5]:
print(df['price'].dtype)
print(df['price'].value_counts())
print(df['price'].isna().sum())

object
price
27.36     2879
21.89     1027
32.84      834
179.43     739
150.00     726
          ...
152.81       1
79.61        1
57.34        1
29.84        1
375.24       1
Name: count, Length: 15071, dtype: int64
0

In [6]:
# Convert price columns to numeric
df['price'] = pd.to_numeric(df['price'], errors='coerce')
df['buyer_price'] = pd.to_numeric(df['buyer_price'], errors='coerce')

# Convert year to numeric (might have empty strings)
df['year'] = pd.to_numeric(df['year'], errors='coerce')

# Check what got converted to NaN
print(f"Price NaNs: {df['price'].isna().sum()}")
print(f"Buyer price NaNs: {df['buyer_price'].isna().sum()}")

Price NaNs: 0
Buyer price NaNs: 0